GET http://localhost:3001/

###

POST http://localhost:3001/api/auth/register

Content-Type: application/json

{
    "fullname": "john depp",
    "email": "patrickhag9@gmail.com",
    "password": "@123Kayonza"
}

###
